server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**

        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/business/**
